image: node:19-alpine

stages:
  - prep
  - test
  - build

install:
  stage: prep
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
  script: npm install --progress=false


unitTest:
  stage: test
  script: npm run test:unit

pages:
  stage: build
  script: npm run build
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      
